config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :topups, except: %i[edit update destroy]

    root to: "users#index"
  end

  get '/dashboard', to: 'dashboard#index'
  get '/budget_menu', to: 'dashboard#budgets'
  get '/history', to: 'dashboard#history'
  root 'dashboard#index'

  devise_for :users
  resources :currencies
  resources :budgets do
    resources :items, only: %i[create destroy]
  end

  resources :transfer, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/models/currency.rb
class Currency < ApplicationRecord
  before_save :update_balance
  before_destroy :deduct_balance

  validates :amount, presence: true

  belongs_to :user

  private
  def update_balance
    user.reload.update(balance: user.balance + amount)
  end

  def deduct_balance
    user.reload.update(balance: user.balance - amount)
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :budget
  
  validates :title, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/topup.rb
class Topup < ApplicationRecord
  before_save do
    user.update!(balance: user.balance + self.amount)
  end

  enum :payment_option, { ecocash: 0, cash: 1 }
  belongs_to :user
  
  validates :amount, presence: true
  validates :payment_option, presence: true
  validate :positive_amount
  validate :poll_url_on_ecocash

  private
  def positive_amount
    errors.add(:base, 'Your amount should be greater than 1') if amount.to_i < 1
  end

  def poll_url_on_ecocash
    errors.add(:base, 'Your ecocash transaction has no poll_url.') if ecocash? && poll_url.blank?
  end
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :receiver, class_name: 'User'
  belongs_to :sender, class_name: 'User'

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validate :sender_has_enough_balance

  after_save :update_balance

  private
  def sender_has_enough_balance
    if sender.balance < amount
      errors.add(:amount, "is greater than sender's balance")
    end
  end

  def update_balance
    sender.reload.update(balance: sender.balance - amount)
    receiver.reload.update(balance: receiver.balance + amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :ecocash_number, presence: true

  has_many :currencies, dependent: :destroy
  has_many :budgets, dependent: :destroy
  has_many :topups, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end

  def transfer(amount, user)
    amount.nil? ? amount = 0 : amount
    current_amount = user.balance + amount
    user.reload.update(balance: current_amount) ? true : false
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :devise_sanitized_params, if: :devise_controller?

  private

  def devise_sanitized_params
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(devise_permitted_params) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(devise_permitted_params) }
  end

  def devise_permitted_params
    %i[first_name last_name email ecocash_number password password_confirmation current_password]
  end

  protected

  def after_sign_in_path_for(_resource)
    dashboard_path
  end

  def after_update_path_for(_resource)
    dashboard_path
  end
  
  def after_sign_up_path_for(_resource)
    dashboard_path
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :authenticate_user!

  def new
    @budgets = Budget.new
  end

  def create
    @budget = current_user.budgets.build(title: params[:title])
    if @budget.save
      redirect_to edit_budget_path(@budget), flash: { notice: "Budget created successfully" }
    else
      redirect_to new_budget_path, flash: { notice: "There was an error creating budget" }   
    end
  end

  def edit
    @budget = Budget.find(params[:id])
    @item = Item.new
    @items = @budget.items
    @account_balance = current_user.balance
    @balance_left = current_user.balance - @items.pluck(:amount).sum
    @balance = @items.pluck(:amount).sum
  end

  def update
    @budget = current_user.budgets.find(params[:id]) 
    if @budget.update(budget_params)
      redirect_to edit_budget_path(@budget), flash: { notice: "Budget updated successfully" }
    else
      redirect_to edit_budget_path(@budget), flash: { notice: "There was an error updating budget" }   
    end  
  end

  def show
    @budget = current_user.budgets.find(params[:id])
    @items = @budget.items
    @balance = @items.pluck(:amount).sum
  end

  def index
    @budgets = current_user.budgets
  end

  def destroy
    @budget = current_user.budgets.find(params[:id])
    if @budget.destroy
      redirect_to budgets_path, flash: { notice: "Budget deleted successfully" }
    else
      redirect_to budgets_path, flash: { notice: "There was an error deleting budget" }   
    end
  end

  private
  def budget_params
    params.require(:budget).permit(:title)
  end

end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :authenticate_user!

  def index
    @currencies = current_user.currencies
  end

  def transfer
    
  end

  def transfer_currency
    @reciever = User.find(params[:receiver_id])
    if current_user.transfer(params[:amount], @reciever)
      redirect_to dashboard_path, flash: { notice: "Transfer successful!" }
    else
      redirect_to transfer_currency_path, flash: { alert: "Transfer was unsuccessful!" }
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end

  def history
    @money_sent = Transfer.where(sender: current_user).order(created_at: :desc)
    @money_received = Transfer.where(receiver: current_user).order(created_at: :desc)
    @currencies = current_user.currencies.order(created_at: :desc)
  end

  def budgets
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = budget.items.new(item_params)

    if @item.save
      redirect_to edit_budget_path(budget), flash: { notice: "Item added successfully" }
    else
      redirect_to edit_budget_path(budget), flash: { notice: "There was an error adding items" }   
    end
  end

  def destroy
    items= budget.items.find(params[:id])
    if items.destroy
      redirect_to request.referer, flash: { notice: "Item deleted successfully" }
    else
      redirect_to request.referer, flash: { notice: "There was an error deleting an item" }   
    end
  end

  private
  
  def item_params
    params.require(:item).permit(:title, :amount)
  end

  def budget
    @budget ||= Budget.find(params[:budget_id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/transfer_controller.rb
class TransferController < ApplicationController
  before_action :authenticate_user!
  def new
    @transfer = Transfer.new
  end

  def create
    @transfer = Transfer.new(transfer_params)
    @transfer.sender = current_user
    @transfer.receiver = receiver
    
    if @transfer.save
      redirect_to dashboard_path, flash: { notice: 'Transfer successful.' }
    else
      redirect_to new_transfer_path, flash: { notice: @transfer.errors.full_messages }
    end
  end

  private
  def transfer_params
    params.require(:transfer).permit(:amount, :receiver_id)
  end

  def receiver
    @receiver ||= User.find(transfer_params[:receiver_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transfer_helper.rb
module TransferHelper
end

app/views/dashboard/budgets.html.erb
<%= link_to 'Main menu', dashboard_path,
  class: 'px-3 py-2 border border-indigo-500 rounded-full 
    hover:text-white hover:bg-indigo-400 hover:border-indigo-400
    font-semibold text-indigo-500
  '
%>

<section class="w-full lg:w-[30%] mt-[5em] mx-auto p-2.5 bg-indigo-100 rounded-lg"> 
  <div class="container mx-auto px-4 py-8 max-w-md">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <%= link_to new_budget_path do %>
        <div 
          class="
            bg-gradient-to-r from-blue-500 to-teal-500
            rounded-lg p-6 shadow-lg text-white transition
            ease-in-out hover:-translate-y-0 hover:scale-90
            duration-300
          "
        >
          <h2 class="text-xl font-semibold mb-2">Add new budget</h2>
          <p class="text-gray-200">Add a new budget.</p>
        </div>
      <% end %>
      
      <%= link_to budgets_path do %>
        <div 
          class="
            bg-gradient-to-r from-emerald-500 to-lime-500 rounded-lg
            p-6 shadow-lg text-white transition ease-in-out
            hover:-translate-y-0 hover:scale-90 duration-300
          "
        >
          <h2 class="text-xl font-semibold mb-2">Your budgets</h2>
          <p class="text-gray-200">View all of your budgets.</p>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/dashboard/history.html.erb
<%= link_to 'Main menu', dashboard_path,
  class: 'px-3 py-2 border border-indigo-500 rounded-full 
    hover:text-white hover:bg-indigo-400 hover:border-indigo-400
    font-semibold text-indigo-500
  '
%>
<section class="mx-auto p-2 bg-gray-100 mt-4">
  <div class="grid grid-cols-1 md:grid-cols-2">
    <div class="w-full col-span-1 md:col-span-2">
      <h1 class="text-6xl text-center">Top ups</h1>
      <div class="grid grid-cols-5 md:grid-cols-7 justify-center gap-4 md:p-2 my-4 md:px-20 text-center">
        <% current_user.topups.each do |topup| %>
          <div 
            class="
              rounded-lg bg-indigo-100 p-2.5 transition
            ease-out-in hover:-translate-y-0 hover:scale-110
            duration-300
              
            "
          >
            <figure class="w-10 h-10 p-2 bg-blue-800 rounded-md mx-auto mb-2">
              <svg width="24" height="24" fill="#FFFFFF">
                <path d="M18.799 7.038c-.496-.535-.799-1.252-.799-2.038 0-1.656 1.344-3 3-3s3 1.344 3 3-1.344 3-3 3c-.146 0-.29-.01-.431-.031l-3.333 6.032c.475.53.764 1.231.764 1.999 0 1.656-1.344 3-3 3s-3-1.344-3-3c0-.583.167-1.127.455-1.587l-2.565-3.547c-.281.087-.58.134-.89.134l-.368-.022-3.355 6.069c.451.525.723 1.208.723 1.953 0 1.656-1.344 3-3 3s-3-1.344-3-3 1.344-3 3-3c.186 0 .367.017.543.049l3.298-5.967c-.52-.539-.841-1.273-.841-2.082 0-1.656 1.344-3 3-3s3 1.344 3 3c0 .617-.187 1.191-.507 1.669l2.527 3.495c.307-.106.637-.164.98-.164.164 0 .325.013.482.039l3.317-6.001zm-3.799 7.962c.552 0 1 .448 1 1s-.448 1-1 1-1-.448-1-1 .448-1 1-1zm-6-8c.552 0 1 .448 1 1s-.448 1-1 1-1-.448-1-1 .448-1 1-1z"></path>
              </svg>
            </figure>
            <h1 class="font-bold"><%= topup.amount %>.00</h2>
            <p><%= topup.payment_option %><p>
            <p><%= topup.created_at.strftime('%d %B %Y') %><p>
          </div>
        <% end %>
      </div>
    </div>

    <div class="w-full">
      <h1 class="text-6xl text-center">Transfers recieved</h1>
      <div class="grid grid-cols-3 justify-center gap-4 md:p-2 my-4 md:px-20 text-center">
        <% @money_received.each do |money| %>
          <div 
            class="
              rounded-lg bg-emerald-100 p-2.5 transition
            ease-out-in hover:-translate-y-0 hover:scale-110
            duration-300
              
            "
          >
            <figure class="w-10 h-10 p-2 bg-emerald-600 rounded-md mx-auto mb-2">
              <svg width="24" height="24" fill="#FFFFFF">
                <path d="M18.799 7.038c-.496-.535-.799-1.252-.799-2.038 0-1.656 1.344-3 3-3s3 1.344 3 3-1.344 3-3 3c-.146 0-.29-.01-.431-.031l-3.333 6.032c.475.53.764 1.231.764 1.999 0 1.656-1.344 3-3 3s-3-1.344-3-3c0-.583.167-1.127.455-1.587l-2.565-3.547c-.281.087-.58.134-.89.134l-.368-.022-3.355 6.069c.451.525.723 1.208.723 1.953 0 1.656-1.344 3-3 3s-3-1.344-3-3 1.344-3 3-3c.186 0 .367.017.543.049l3.298-5.967c-.52-.539-.841-1.273-.841-2.082 0-1.656 1.344-3 3-3s3 1.344 3 3c0 .617-.187 1.191-.507 1.669l2.527 3.495c.307-.106.637-.164.98-.164.164 0 .325.013.482.039l3.317-6.001zm-3.799 7.962c.552 0 1 .448 1 1s-.448 1-1 1-1-.448-1-1 .448-1 1-1zm-6-8c.552 0 1 .448 1 1s-.448 1-1 1-1-.448-1-1 .448-1 1-1z"></path>
              </svg>
            </figure>
            <h1 class="font-bold"><%= money.amount %>.00</h2>
            <p><%= money.created_at.strftime('%d %B %Y') %><p>
          </div>
        <% end %>
      </div>
    </div>

    <div class="w-full">
      <h1 class="text-6xl text-center">Transfers sent</h1>
      <div class="grid grid-cols-3 justify-center gap-4 md:p-2 my-4 text-center">
        
        <% @money_sent.each do |money| %>
          <div 
            class="
              rounded-lg bg-yellow-100 p-2.5 transition
            ease-out-in hover:-translate-y-0 hover:scale-110
            duration-300
              
            "
          >
            <figure class="w-10 h-10 p-2 bg-yellow-600 rounded-md mx-auto mb-2">
              <svg width="24" height="24" fill="#FFFFFF">
                <path d="M18.799 7.038c-.496-.535-.799-1.252-.799-2.038 0-1.656 1.344-3 3-3s3 1.344 3 3-1.344 3-3 3c-.146 0-.29-.01-.431-.031l-3.333 6.032c.475.53.764 1.231.764 1.999 0 1.656-1.344 3-3 3s-3-1.344-3-3c0-.583.167-1.127.455-1.587l-2.565-3.547c-.281.087-.58.134-.89.134l-.368-.022-3.355 6.069c.451.525.723 1.208.723 1.953 0 1.656-1.344 3-3 3s-3-1.344-3-3 1.344-3 3-3c.186 0 .367.017.543.049l3.298-5.967c-.52-.539-.841-1.273-.841-2.082 0-1.656 1.344-3 3-3s3 1.344 3 3c0 .617-.187 1.191-.507 1.669l2.527 3.495c.307-.106.637-.164.98-.164.164 0 .325.013.482.039l3.317-6.001zm-3.799 7.962c.552 0 1 .448 1 1s-.448 1-1 1-1-.448-1-1 .448-1 1-1zm-6-8c.552 0 1 .448 1 1s-.448 1-1 1-1-.448-1-1 .448-1 1-1z"></path>
              </svg>
            </figure>
            <h1 class="font-bold"><%= money.amount %>.00</h2>
            <p><%= money.created_at.strftime('%d %B %Y') %><p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/dashboard/index.html.erb
<section class="w-full lg:w-[30%] mt-[3em] mx-auto p-2.5 bg-indigo-100 rounded-lg"> 
  <div class="container mx-auto px-4 py-8 max-w-md">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <%= link_to new_transfer_path do %>
        <div 
          class="
            bg-gradient-to-r from-yellow-500 to-amber-500
            rounded-lg p-6 shadow-lg text-white transition
            ease-out-in hover:-translate-y-0 hover:scale-110
            duration-300
          "
        >
          <h2 class="text-xl font-semibold mb-2">Transfer funds</h2>
          <p class="text-gray-200">Transfer funds to a friend.</p>
        </div>
      <% end %>
      
      <%= link_to history_path do %>
        <div 
          class="
            bg-gradient-to-r from-blue-500 to-teal-500 rounded-lg
            p-6 shadow-lg text-white transitionease-out-in 
            hover:-translate-y-0 hover:scale-110 duration-300
          "
        >
          <h2 class="text-xl font-semibold mb-2">Account History</h2>
          <p class="text-gray-200">View your activity.</p>
        </div>
      <% end %>

      <%= link_to budget_menu_path do %>
        <div 
          class="
            bg-gradient-to-r from-emerald-500 to-lime-500 rounded-lg p-6
            shadow-lg text-white transitionease-out-in hover:-translate-y-0
            hover:scale-110 duration-300
          "
        >
          <h2 class="text-xl font-semibold mb-2">Plan a Budget</h2>
          <p class="text-gray-200">Plan and adjust your budget.<p>
        </div>
      <% end %>

       <%= link_to edit_user_registration_path do %>
        <div 
          class="
            bg-gradient-to-r from-purple-500 to-pink-500 rounded-lg p-6 shadow-lg
            text-white transitionease-out-in hover:-translate-y-0 hover:scale-110 
            duration-300
          "
        >
          <h2 class="text-xl font-semibold mb-2">Account Settings</h2>
          <p class="text-gray-200">Configure your account</p>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/static_pages/home.html.erb
<div>
  <h1 class="font-bold text-4xl">StaticPages#home</h1>
  <p>Find me in app/views/static_pages/home.html.erb</p>
</div>