config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :topups, except: %i[edit update destroy]

    root to: "users#index"
  end

  get '/dashboard', to: 'dashboard#index'
  get '/budget_menu', to: 'dashboard#budgets'
  get '/history', to: 'dashboard#history'
  root 'dashboard#index'

  devise_for :users
  resources :currencies
  resources :budgets do
    resources :items, only: %i[create destroy]
  end

  resources :transfer, only: %i[new create]
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :authenticate_user!

  def new
    @budgets = Budget.new
  end

  def create
    @budget = current_user.budgets.build(title: params[:title])
    if @budget.save
      redirect_to edit_budget_path(@budget), flash: { notice: "Budget created successfully" }
    else
      redirect_to new_budget_path, flash: { notice: "There was an error creating budget" }   
    end
  end

  def edit
    @budget = Budget.find(params[:id])
    @item = Item.new
    @items = @budget.items
    @account_balance = current_user.balance
    @balance_left = current_user.balance - @items.pluck(:amount).sum
    @balance = @items.pluck(:amount).sum
  end

  def update
    @budget = current_user.budgets.find(params[:id]) 
    if @budget.update(budget_params)
      redirect_to edit_budget_path(@budget), flash: { notice: "Budget updated successfully" }
    else
      redirect_to edit_budget_path(@budget), flash: { notice: "There was an error updating budget" }   
    end  
  end

  def show
    @budget = current_user.budgets.find(params[:id])
    @items = @budget.items
    @balance = @items.pluck(:amount).sum
  end

  def index
    @budgets = current_user.budgets
  end

  def destroy
    @budget = current_user.budgets.find(params[:id])
    if @budget.destroy
      redirect_to budgets_path, flash: { notice: "Budget deleted successfully" }
    else
      redirect_to budgets_path, flash: { notice: "There was an error deleting budget" }   
    end
  end

  private
  def budget_params
    params.require(:budget).permit(:title)
  end

end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/edit.html.erb
<h1 class="text-center md:text-start">
  <%= link_to 'Budget menu', budget_menu_path,
    class: 'px-3 py-2 border border-indigo-500 rounded-full 
      hover:text-white hover:bg-indigo-400 hover:border-indigo-400
      font-semibold text-indigo-500
    '
  %>
  <%= link_to 'Main menu', dashboard_path,
    class: 'px-3 py-2 border border-indigo-500 rounded-full 
      hover:text-white hover:bg-indigo-400 hover:border-indigo-400
      font-semibold text-indigo-500
    '
  %>
</h1>
<% @account_balance.negative? ? classes = 'bg-red-600' : classes = 'bg-emerald-600' %>
<section class="w-4/5 mx-auto md:p-2">
  <h1 class="text-4xl font-bold text-center text-blue-500 mb-2">
        Plan <span class="text-teal-500">Budget</span></h1>
  <div class="grid lg:grid-cols-2 grid-cols-1 p-1 bg-indigo-100 rounded gap-2">
    <div class="rounded-lg p-2">
      <div class="bg-white p-1 rounded-lg mb-4">
        <h1 class="text-2xl font-bold text-center text-blue-500 mb-5">
        Edit <span class="text-teal-500">Budget</span></h1>
        <%= form_with(model: @budget, url: budget_path, data: { "turbo-method": 'put' } ) do |f| %>
          <div class="flex flex-row gap-4 w-full p-4 justify-center"> 
            <div class="base-1/2 w-full">
              <%= f.label 'Title',
                class: "block text-gray-600 cursor-text text-sm leading-[140%] font-normal mb-1" 
              %>
              <%= f.text_field :title, required: true,
                class: "rounded border border-gray-200 text-sm w-full font-normal leading-[18px]
                  text-black tracking-[0px] appearance-none block h- m-0 p-[11px] 
                  focus:ring-2 ring-offset-2  ring-gray-900 outline-0", max: current_user.balance
              %>
            </div>
          </div>
          <div class="base-1/2 w-1/4 mx-auto">
            <%= f.submit 'Update', class: 'font-bold w-full bg-orange-400 hover:bg-orange-500 text-white rounded-full px-3 py-2' %>
          </div>
        <% end %>
      </div>
      <% if @account_balance > 0 %>
        <div class="bg-white p-1 rounded-lg">
          <h1 class="text-2xl font-bold text-center text-blue-500 mb-3">
          Add <span class="text-teal-500">Item</span></h1>
          <%= form_with(model: @item, url: budget_items_path(@budget, @item), data: { "turbo-method": 'put' } ) do |f| %>
            <div class="flex flex-row gap-4 w-full p-4 justify-center"> 
              <div class="base-1/2 w-full">
                <%= f.label 'Title',
                  class: "block text-gray-600 cursor-text text-sm leading-[140%] font-normal mb-1" 
                %>
                <%= f.text_field :title, required: true,
                  class: "rounded border border-gray-200 text-sm w-full font-normal leading-[18px]
                    text-black tracking-[0px] appearance-none block h- m-0 p-[11px] 
                    focus:ring-2 ring-offset-2  ring-gray-900 outline-0"
                %>
              </div>
              <div class="base-1/2 w-full">
                <%= f.label 'Amount ($)',
                  class: "block text-gray-600 cursor-text text-sm leading-[140%] font-normal mb-1" 
                %>
                <%= f.number_field :amount, required: true,
                  class: "rounded border border-gray-200 text-sm w-full font-normal leading-[18px]
                    text-black tracking-[0px] appearance-none block h- m-0 p-[11px] 
                    focus:ring-2 ring-offset-2  ring-gray-900 outline-0", max: @balance_left
                %>
              </div>
            </div>
            <div class="base-1/2 w-1/4 mx-auto">
              <%= f.submit 'Add', class: 'font-bold w-full bg-orange-400 hover:bg-orange-500 text-white rounded-full px-3 py-2' %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="shadow-lg p-2 rounded-lg">
      <h1 class="text-center mb-3 text-xl" >Budget Items</h1>
      <table class="table-auto border-collapse border border-slate-400 w-full mx-2 lg:mx-auto">
        <thead>
          <tr>
            <th class="border border-slate-300">Title</th>
            <th class="border border-slate-300">Amount ($)</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr class="text-center">
            <td class="border border-slate-300"><%= item.title %></td>
            <td class="border border-slate-300"><%= item.amount %></td>
            <td class="border border-slate-300 text-center py-1 px-0">
              <%= button_to 'Delete' ,budget_item_path(@budget, item), class: 'px-2 py-1 font-bold text-white bg-red-500 rounded hover:bg-red-600', method: :delete %>
            </td>
          </tr>
          <% end %>
          
          <tr class="text-center">
            <td></td>
            <td></td>
            <td>
              <h1 class="font-bold text-white mt-1 px-2 py-1 <%=classes%> rounded">
                Total: 
                <%= @balance %>
              </h1>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/budgets/index.html.erb
<h1 class="text-center md:text-start">
  <%= link_to 'Budget menu', budget_menu_path,
    class: 'px-3 py-2 border border-indigo-500 rounded-full 
      hover:text-white hover:bg-indigo-400 hover:border-indigo-400
      font-semibold text-indigo-500
    '
  %>
  <%= link_to 'Main menu', dashboard_path,
    class: 'px-3 py-2 border border-indigo-500 rounded-full 
      hover:text-white hover:bg-indigo-400 hover:border-indigo-400
      font-semibold text-indigo-500
    '
  %>
</h1>
<section>
  <h1 class="text-center text-2xl my-4">Budgets</h1>

  <table class="table-auto border-collapse border border-slate-400 w-full lg:w-3/5 mx-2 lg:mx-auto">
  <thead>
      <tr>
        <th class="border border-slate-300">Id</th>
        <th class="border border-slate-300">Title</th>
        <th class="border border-slate-300">Created at</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      
        <% @budgets.each do |budget| %>
        <tr class="text-center">
          <td class="border border-slate-300"><%= budget.id %></td>
          <td class="border border-slate-300"><%= budget.title %></td>
          <td class="border border-slate-300"><%= budget.created_at.strftime('%d %B %Y') %></td>
          <td class="border border-slate-300 text-center py-1 px-0">
            <%= link_to 'View', budget_path(budget), class: 'px-2 py-1 font-bold text-white bg-orange-500 rounded hover:bg-orange-600' %>
            <%= link_to 'Edit', edit_budget_path(budget), class: 'px-2 py-1 font-bold text-white bg-blue-500 rounded hover:bg-blue-600' %>
          </td>
        </tr>
        <% end %>
      
    </tbody>
  </table>
</section>

app/views/budgets/new.html.erb
<%= link_to 'Budget menu', budget_menu_path,
  class: 'px-3 py-2 border border-indigo-500 rounded-full 
    hover:text-white hover:bg-indigo-400 hover:border-indigo-400
    font-semibold text-indigo-500
  '
%>
<section class="w-full lg:w-[50%] mt-[6em] mx-auto md:p-2 md:p-8 bg-gray-100"> 
  <div class="w-full">
    <h1 class="text-2xl font-bold text-center text-blue-500 mb-5">
      New <span class="text-teal-500">Budget</span></h1>
    <%= form_with(model: @budget, url: budgets_path, data: { turbo: false } ) do |f| %>
      <div class="flex flex-row gap-4 w-full mb-4 justify-center"> 
        <div class="base-1/2 w-full md:w-1/2">
          <%= f.label 'Title',
            class: "block text-gray-600 cursor-text text-sm leading-[140%] font-normal mb-1" 
          %>
          <%= f.text_field :title, required: true,
            class: "rounded border border-gray-200 text-sm w-full font-normal leading-[18px]
              text-black tracking-[0px] appearance-none block h- m-0 p-[11px] 
              focus:ring-2 ring-offset-2  ring-gray-900 outline-0", max: current_user.balance
          %>
        </div>
      </div>
      <div class="base-1/2 w-1/4 mx-auto">
        <%= f.submit 'Create', class: 'font-bold w-full bg-orange-400 hover:bg-orange-500 text-white rounded-full px-3 py-2' %>
      </div>
    <% end %>
  </div>
</section>

app/views/budgets/show.html.erb
<h1 class="text-center md:text-start">
  <%= link_to 'Budget menu', budget_menu_path,
    class: 'px-3 py-2 border border-indigo-500 rounded-full 
      hover:text-white hover:bg-indigo-400 hover:border-indigo-400
      font-semibold text-indigo-500
    '
  %>
  <%= link_to 'Main menu', dashboard_path,
    class: 'px-3 py-2 border border-indigo-500 rounded-full 
      hover:text-white hover:bg-indigo-400 hover:border-indigo-400
      font-semibold text-indigo-500
    '
  %>
</h1>

<% @balance.negative? ? classes = 'bg-red-600' : classes = 'bg-emerald-600' %>

<section>
  <div class="shadow-lg p-2 rounded-lg w-full md:w-3/5 mx-auto">
      <h1 class="text-center mb-3 text-xl" ><%= @budget.title %> Budget Items</h1>
      <table class="table-auto border-collapse border border-slate-400 w-full mx-2 lg:mx-auto">
        <thead>
          <tr>
            <th class="border border-slate-300">Title</th>
            <th class="border border-slate-300">Amount ($)</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr class="text-center">
            <td class="border border-slate-300"><%= item.title %></td>
            <td class="border border-slate-300"><%= item.amount %></td>
          </tr>
          <% end %>
          
          <tr class="text-center">
            <td></td>
            <td>
              <h1 class="font-bold text-white mt-1 px-2 py-1 <%=classes%> rounded">
                Total: 
                <%= @balance %>
              </h1>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
</section>