config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :topups, except: %i[edit update destroy]

    root to: "users#index"
  end

  get '/dashboard', to: 'dashboard#index'
  get '/budget_menu', to: 'dashboard#budgets'
  get '/history', to: 'dashboard#history'
  root 'dashboard#index'

  devise_for :users
  resources :currencies
  resources :budgets do
    resources :items, only: %i[create destroy]
  end

  resources :transfer, only: %i[new create]
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :receiver, class_name: 'User'
  belongs_to :sender, class_name: 'User'

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validate :sender_has_enough_balance

  after_save :update_balance

  private
  def sender_has_enough_balance
    if sender.balance < amount
      errors.add(:amount, "is greater than sender's balance")
    end
  end

  def update_balance
    sender.reload.update(balance: sender.balance - amount)
    receiver.reload.update(balance: receiver.balance + amount)
  end
end

app/controllers/transfer_controller.rb
class TransferController < ApplicationController
  before_action :authenticate_user!
  def new
    @transfer = Transfer.new
  end

  def create
    @transfer = Transfer.new(transfer_params)
    @transfer.sender = current_user
    @transfer.receiver = receiver
    
    if @transfer.save
      redirect_to dashboard_path, flash: { notice: 'Transfer successful.' }
    else
      redirect_to new_transfer_path, flash: { notice: @transfer.errors.full_messages }
    end
  end

  private
  def transfer_params
    params.require(:transfer).permit(:amount, :receiver_id)
  end

  def receiver
    @receiver ||= User.find(transfer_params[:receiver_id])
  end
end

app/helpers/transfer_helper.rb
module TransferHelper
end

app/views/transfer/new.html.erb
<%= link_to 'Main menu', dashboard_path,
  class: 'px-3 py-2 border border-indigo-500 rounded-full 
    hover:text-white hover:bg-indigo-400 hover:border-indigo-400
    font-semibold text-indigo-500 mx-4 fixed relative
  '
%>
<section class="w-full lg:w-[50%] mt-[6em] mx-auto md:p-2 md:p-8 bg-gray-100"> 
  <div class="w-full">
    <h1 class="text-2xl font-bold text-center text-orange-500 mb-5">Transfer Money</h1>
    <%= form_with(model: @transfer, url: transfer_index_path, data: { turbo: false } ) do |f| %>
      <div class="flex flex-row gap-4 w-full mb-4"> 
        <div class="base-1/2 w-full">
          <%= f.label :receiver, 
            class: "block text-gray-600 cursor-text text-sm leading-[140%] font-normal mb-1" 
          %>
          <%= f.collection_select :receiver_id, User.where.not(id: current_user.id), :id, :full_name,
            { prompt: "Select a user" }, required: true,
            class: "rounded border border-gray-200 text-sm w-full font-normal leading-[18px]
              text-black tracking-[0px] appearance-none block h- m-0 p-[11px] 
              focus:ring-2 ring-offset-2  ring-gray-900 outline-0"
          %>

        </div>
        <div class="base-1/2 w-full">
          <%= f.label 'Amount ($)', 
            class: "block text-gray-600 cursor-text text-sm leading-[140%] font-normal mb-1" 
          %>
          <%= f.number_field :amount, required: true,
            class: "rounded border border-gray-200 text-sm w-full font-normal leading-[18px]
              text-black tracking-[0px] appearance-none block h- m-0 p-[11px] 
              focus:ring-2 ring-offset-2  ring-gray-900 outline-0", max: current_user.balance
          %>
        </div>
      </div>
      <div class="base-1/2 w-1/4 mx-auto">
        <%= f.submit 'Send', class: 'font-bold w-full bg-orange-400 hover:bg-orange-500 text-white rounded-full px-3 py-2' %>
      </div>
    <% end %>
  </div>
</section>